In [1]:
import numpy as np
import random

In [2]:
def mn_matrix(M: int, N: int):
    a = np.random.randn(M, N)
    return a

In [3]:
a = mn_matrix(2, 4)
a

array([[ 1.18887268, -1.55999501, -0.58662178, -1.90979924],
       [ 0.16906184,  0.22613497, -1.05216704,  1.32928716]])

In [4]:
def k_vector(M: int):
    a = np.random.randn(M)
    return a

In [5]:
a = k_vector(5)
a

array([ 1.28759469,  0.63877067,  0.33669195, -0.81296204, -0.91624772])

In [6]:
def mn_nk(m_1: list[int], m_2: list[int]):
    if len(m_1[0]) != len(m_2):
        raise ValueError("N from m_1 should be equal to N in m_2")

    result = []
    for i in range(len(m_1)):
        row = []
        for j in range(len(m_2[0])):
            element = 0
            for k in range(len(m_2)):
                element += m_1[i][k] * m_2[k][j]
            row.append(element)
        result.append(row)

    return result

In [7]:
def mn_n(m_1: list[int], v_1: list[int]):
    if len(m_1[0]) != len(v_1):
        raise ValueError("N from matrix should be equal to N in vector")

    result = []
    for i in range(len(m_1)):
        element = 0
        for k in range(len(v_1)):
            element += m_1[i][k] * v_1[k]
        result.append(element)

    return result

In [8]:
def m_mn(v, G):
    result = []
    for i in range(len(G[0])):
        total = 0
        for j in range(len(v)):
            total += v[j] * G[j][i]
        result.append(total)
    return result

In [9]:
def v_v(v_1: list[int], v_2: list[int]):
    if len(v_1) != len(v_2):
        raise ValueError("N should be equal to both vectors")

    result = 0
    for i in range(len(v_1)):
        result += v_1[i] * v_2[i]
        
    return result

In [10]:
M = np.random.randint(1000, 1100)
N = np.random.randint(1000, 1100)
K = np.random.randint(1000, 1100)

mn = mn_matrix(M, N)
nk = mn_matrix(N, K)

m = k_vector(M)
n = k_vector(N)

mn, nk, m, n

(array([[-0.22611919,  0.26822149,  1.8198475 , ...,  0.51331015,
         -0.42889905,  0.12919502],
        [ 0.5052512 ,  0.25772846,  0.69242373, ..., -0.68235511,
         -0.33117512, -0.23990864],
        [ 0.53871935,  1.95824251,  1.48670587, ...,  0.5565508 ,
         -0.85442032,  0.04907351],
        ...,
        [-1.35588916, -0.43672413, -1.12493554, ..., -1.24518413,
         -1.36210956,  1.30901199],
        [ 0.54971028,  0.80822848, -0.59189512, ...,  0.04056385,
          1.05601146,  0.24462701],
        [-0.3893757 , -0.98181004, -1.52541695, ...,  1.62812708,
          0.66988426, -0.34487916]]),
 array([[ 0.20931875, -1.13763062,  1.00729   , ...,  0.11640356,
         -0.0491704 ,  1.22142022],
        [-0.92985115,  1.71400945, -0.49683004, ...,  0.93631258,
          0.82560233,  0.10873258],
        [ 1.66818162, -1.03567394,  0.2729793 , ..., -1.21702707,
          0.15587798, -0.47689045],
        ...,
        [ 0.98225683, -1.49359726,  0.5811692 , ...,  

In [11]:
import time

mn_custom = mn_matrix(1000, 1000)
nk_custom = mn_matrix(1000, 1000)

start = time.time()
a = mn_nk(mn_custom, nk_custom)
end = time.time()
print(f"Custom matrix multiplication: {end - start}")

start = time.time()
b = np.matmul(mn_custom, nk_custom)
end = time.time()
print(f"Numpy matrix multiplication: {end - start}")

np.allclose(a, b, atol=1e-6)

Custom matrix multiplication: 526.0591292381287
Numpy matrix multiplication: 0.025685548782348633


True

In [12]:
start = time.time()
a = mn_n(mn, n)
end = time.time()
print(f"Custom matrix, vector multiplication: {end - start}")

start = time.time()
b = np.dot(mn, n)
end = time.time()
print(f"Numpy matrix, vector multiplication: {end - start}")

np.allclose(a, b, atol=1e-6)

Custom matrix, vector multiplication: 0.4949076175689697
Numpy matrix, vector multiplication: 0.008437156677246094


True

In [13]:
start = time.time()
a = m_mn(m, mn)
end = time.time()
print(f"Custom vector, matrix multiplication: {end - start}")

start = time.time()
b = np.dot(m, mn)
end = time.time()
print(f"Numpy vector, matrix multiplication: {end - start}")

np.allclose(a, b, atol=1e-6)

Custom vector, matrix multiplication: 0.5820856094360352
Numpy vector, matrix multiplication: 0.0006687641143798828


True

In [14]:
v_1 = k_vector(M)
v_2 = k_vector(M)

v_1, v_2

(array([ 0.13715039,  1.52143926,  1.00870821, ..., -1.67839003,
         0.31503219,  0.87787976]),
 array([ 0.26393558, -0.50838975, -1.34818735, ..., -0.57569411,
        -0.8293902 , -0.35555633]))

In [15]:
start = time.time()
a = v_v(v_1, v_2)
end = time.time()
print(f"Custom vector, vector multiplication: {end - start}")

start = time.time()
b = np.matmul(v_1, v_2)
end = time.time()
print(f"Numpy vector, vector multiplication: {end - start}")

np.allclose(a, b, atol=1e-6)

Custom vector, vector multiplication: 0.0008361339569091797
Numpy vector, vector multiplication: 0.00010704994201660156


True