In [1]:
import numpy as np
import random

In [2]:
def mn_matrix(M: int, N: int):
    a = np.full((M, N), random.uniform(0, 1))
    return a

In [3]:
a = mn_matrix(2, 4)
a

array([[0.09129917, 0.09129917, 0.09129917, 0.09129917],
       [0.09129917, 0.09129917, 0.09129917, 0.09129917]])

In [4]:
def k_vector(M: int):
    a = np.full(M, random.uniform(0, 1))
    return a

In [5]:
a = k_vector(5)
a

array([0.57827384, 0.57827384, 0.57827384, 0.57827384, 0.57827384])

In [67]:
def mn_nk(m_1: list[int], m_2: list[int]):
    if len(m_1[0]) != len(m_2):
        raise ValueError("N from m_1 should be equal to N in m_2")

    result = []
    for i in range(len(m_1)):
        row = []
        for j in range(len(m_2[0])):
            element = 0
            for k in range(len(m_2)):
                element += m_1[i][k] * m_2[k][j]
            row.append(element)
        result.append(row)

    return result

In [7]:
def mn_n(m_1: list[int], v_1: list[int]):
    if len(m_1[0]) != len(v_1):
        raise ValueError("N from matrix should be equal to N in vector")

    result = []
    for i in range(len(m_1)):
        element = 0
        for k in range(len(v_1)):
            element += m_1[i][k] * v_1[k]
        result.append(element)

    return result

In [23]:
def m_mn(v_1: list[int], m_1: list[int]):
    if len(v_1) != len(m_1):
        raise ValueError("M from vector should be equal to M in matrix")

    result = []
    for i in range(len(v_1)):
        element = 0
        for k in range(len(v_1)):
            element += v_1[k] * m_1[k][i]
        result.append(element)
        
    return result

In [52]:
def v_v(v_1: list[int], v_2: list[int]):
    if len(v_1) != len(v_2):
        raise ValueError("N should be equal to both vectors")

    result = 0
    for i in range(len(v_1)):
        result += v_1[i] * v_2[i]
    # Element-wise multiplication
    # for i in range(len(v_1)):
    #     row = []
    #     element = 0
    #     for k in range(len(v_1)):
    #         element = v_1[i] * v_2[k]
    #         row.append(element)
    #     result.append(row)
        
    return result

In [10]:
M = np.random.randint(1000, 10001)
N = np.random.randint(1000, 10001)
K = np.random.randint(1000, 10001)

mn = mn_matrix(M, N)
nk = mn_matrix(N, K)

m = k_vector(M)
n = k_vector(N)

mn, nk, m, n

(array([[0.04659982, 0.04659982, 0.04659982, ..., 0.04659982, 0.04659982,
         0.04659982],
        [0.04659982, 0.04659982, 0.04659982, ..., 0.04659982, 0.04659982,
         0.04659982],
        [0.04659982, 0.04659982, 0.04659982, ..., 0.04659982, 0.04659982,
         0.04659982],
        ...,
        [0.04659982, 0.04659982, 0.04659982, ..., 0.04659982, 0.04659982,
         0.04659982],
        [0.04659982, 0.04659982, 0.04659982, ..., 0.04659982, 0.04659982,
         0.04659982],
        [0.04659982, 0.04659982, 0.04659982, ..., 0.04659982, 0.04659982,
         0.04659982]]),
 array([[0.06727651, 0.06727651, 0.06727651, ..., 0.06727651, 0.06727651,
         0.06727651],
        [0.06727651, 0.06727651, 0.06727651, ..., 0.06727651, 0.06727651,
         0.06727651],
        [0.06727651, 0.06727651, 0.06727651, ..., 0.06727651, 0.06727651,
         0.06727651],
        ...,
        [0.06727651, 0.06727651, 0.06727651, ..., 0.06727651, 0.06727651,
         0.06727651],
        [0.0

In [ ]:
import time

# start = time.time()
# a = mn_nk(mn, nk)
# end = time.time()
# print(f"Custom matrix multiplication: {end}")

# start = time.time()
# b = np.matmul(mn, nk)
# end = time.time()
# print(f"Numpy matrix multiplication: {end}")

# print(f"{a[-1][-1]:.7f}, {b[-1][-1]:.7f}")

# a, b

In [33]:
start = time.time()
a = mn_n(mn, n)
end = time.time()
print(f"Custom matrix, vector multiplication: {end}")

start = time.time()
b = np.dot(mn, n)
end = time.time()
print(f"Numpy matrix, vector multiplication: {end}")

print(f"{a[-1]:.7f}, {b[-1]:.7f}")

a, b

Custom matrix, vector multiplication: 1708343651.0461593
Numpy matrix, vector multiplication: 1708343651.0512607
319.5404700, 319.5404700


([319.54047003619894,
  319.54047003619894,
  319.54047003619894,
  319.54047003619894,
  319.54047003619894,
  319.54047003619894,
  319.54047003619894,
  319.54047003619894,
  319.54047003619894,
  319.54047003619894,
  319.54047003619894,
  319.54047003619894,
  319.54047003619894,
  319.54047003619894,
  319.54047003619894,
  319.54047003619894,
  319.54047003619894,
  319.54047003619894,
  319.54047003619894,
  319.54047003619894,
  319.54047003619894,
  319.54047003619894,
  319.54047003619894,
  319.54047003619894,
  319.54047003619894,
  319.54047003619894,
  319.54047003619894,
  319.54047003619894,
  319.54047003619894,
  319.54047003619894,
  319.54047003619894,
  319.54047003619894,
  319.54047003619894,
  319.54047003619894,
  319.54047003619894,
  319.54047003619894,
  319.54047003619894,
  319.54047003619894,
  319.54047003619894,
  319.54047003619894,
  319.54047003619894,
  319.54047003619894,
  319.54047003619894,
  319.54047003619894,
  319.54047003619894,
  319.5404

In [34]:
start = time.time()
a = m_mn(m, mn)
end = time.time()
print(f"Custom vector, matrix multiplication: {end}")

start = time.time()
b = np.matmul(m, mn)
end = time.time()
print(f"Numpy vector, matrix multiplication: {end}")

print(f"{a[-1]:.7f}, {b[-1]:.7f}")

a, b

Custom vector, matrix multiplication: 1708343696.719782
Numpy vector, matrix multiplication: 1708343696.7246637
110.3894317, 110.3894317


([110.38943170116785,
  110.38943170116785,
  110.38943170116785,
  110.38943170116785,
  110.38943170116785,
  110.38943170116785,
  110.38943170116785,
  110.38943170116785,
  110.38943170116785,
  110.38943170116785,
  110.38943170116785,
  110.38943170116785,
  110.38943170116785,
  110.38943170116785,
  110.38943170116785,
  110.38943170116785,
  110.38943170116785,
  110.38943170116785,
  110.38943170116785,
  110.38943170116785,
  110.38943170116785,
  110.38943170116785,
  110.38943170116785,
  110.38943170116785,
  110.38943170116785,
  110.38943170116785,
  110.38943170116785,
  110.38943170116785,
  110.38943170116785,
  110.38943170116785,
  110.38943170116785,
  110.38943170116785,
  110.38943170116785,
  110.38943170116785,
  110.38943170116785,
  110.38943170116785,
  110.38943170116785,
  110.38943170116785,
  110.38943170116785,
  110.38943170116785,
  110.38943170116785,
  110.38943170116785,
  110.38943170116785,
  110.38943170116785,
  110.38943170116785,
  110.3894

In [36]:
v_1 = k_vector(M)
v_2 = k_vector(M)

v_1, v_2

(array([0.73797323, 0.73797323, 0.73797323, ..., 0.73797323, 0.73797323,
        0.73797323]),
 array([0.97862592, 0.97862592, 0.97862592, ..., 0.97862592, 0.97862592,
        0.97862592]))

In [63]:
start = time.time()
a = v_v(v_1, v_2)
end = time.time()
print(f"Custom vector, vector multiplication: {end}")

start = time.time()
b = np.matmul(v_1, v_2)
end = time.time()
print(f"Numpy vector, vector multiplication: {end}")

print(f"{a:.7f}, {b:.7f}")

a, b

Custom vector, vector multiplication: 1708345198.5240817
Numpy vector, vector multiplication: 1708345198.5246284
2222.2085839, 2222.2085839


(2222.208583924951, 2222.2085839250058)