In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
df = pd.read_csv('Wine.csv')

X = df.drop(['Customer_Segment'], axis=1)
Y = df['Customer_Segment']

In [3]:
X

Alcohol  Malic_Acid   Ash  Ash_Alcanity  Magnesium  Total_Phenols  \
0      14.23        1.71  2.43          15.6        127           2.80   
1      13.20        1.78  2.14          11.2        100           2.65   
2      13.16        2.36  2.67          18.6        101           2.80   
3      14.37        1.95  2.50          16.8        113           3.85   
4      13.24        2.59  2.87          21.0        118           2.80   
..       ...         ...   ...           ...        ...            ...   
173    13.71        5.65  2.45          20.5         95           1.68   
174    13.40        3.91  2.48          23.0        102           1.80   
175    13.27        4.28  2.26          20.0        120           1.59   
176    13.17        2.59  2.37          20.0        120           1.65   
177    14.13        4.10  2.74          24.5         96           2.05   

     Flavanoids  Nonflavanoid_Phenols  Proanthocyanins  Color_Intensity   Hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     OD280  Proline  
0     3.92     1065  
1     3.40     1050  
2     3.17     1185  
3     3.45     1480  
4     2.93      735  
..     ...      ...  
173   1.74      740  
174   1.56      750  
175   1.56      835  
176   1.62      840  
177   1.60      560  

[178 rows x 13 columns]

In [4]:
Y

0      1
1      1
2      1
3      1
4      1
      ..
173    3
174    3
175    3
176    3
177    3
Name: Customer_Segment, Length: 178, dtype: int64

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.33, random_state=42)

In [6]:
scaler = StandardScaler()

x_scaled_train = scaler.fit_transform(X_train)
x_scaled_test = scaler.transform(X_test)

In [7]:
for n_components in [3, 8, 13]:
    pca = PCA(n_components=n_components)
    x_pca_train = pca.fit_transform(x_scaled_train)
    x_pca_test = pca.transform(x_scaled_test)

    # Класифікатор DecisionTree
    clf_dt = DecisionTreeClassifier(max_depth=2, random_state=0)
    clf_dt.fit(x_pca_train, y_train)
    y_pred_dt = clf_dt.predict(x_pca_test)

    print(f'\nDecisionTree with {n_components} components:')
    print(f'Accuracy: {accuracy_score(y_test, y_pred_dt):.2f}')
    print(f'Confusion matrix:\n{confusion_matrix(y_test, y_pred_dt)}')
    
    # Класифікатор RandomForest
    clf_rf = RandomForestClassifier(max_depth=2, random_state=0)
    clf_rf.fit(x_pca_train, y_train)
    y_pred_rf = clf_rf.predict(x_pca_test)

    print(f'\nRandomForest with {n_components} components:')
    print(f'Accuracy: {accuracy_score(y_test, y_pred_rf):.2f}')
    print(f'Confusion matrix:\n{confusion_matrix(y_test, y_pred_rf)}')


DecisionTree with 3 components:
Accuracy: 0.95
Confusion matrix:
[[18  2  0]
 [ 0 23  1]
 [ 0  0 15]]

RandomForest with 3 components:
Accuracy: 0.97
Confusion matrix:
[[18  2  0]
 [ 0 24  0]
 [ 0  0 15]]

DecisionTree with 8 components:
Accuracy: 0.95
Confusion matrix:
[[18  2  0]
 [ 0 23  1]
 [ 0  0 15]]

RandomForest with 8 components:
Accuracy: 0.93
Confusion matrix:
[[18  2  0]
 [ 0 24  0]
 [ 0  2 13]]

DecisionTree with 13 components:
Accuracy: 0.95
Confusion matrix:
[[18  2  0]
 [ 0 23  1]
 [ 0  0 15]]

RandomForest with 13 components:
Accuracy: 0.97
Confusion matrix:
[[18  2  0]
 [ 0 24  0]
 [ 0  0 15]]
