In [2]:
import numpy as np
import pandas as pd

In [3]:
def NOT(a):
    return 1 - a

def AND(a, b):
    return np.minimum(a, b)

def OR(a, b):
    return np.maximum(a, b)

def IMP(a, b):
    return OR(AND(a, b), NOT(a))

def EQU(a, b):
    return AND(OR(NOT(a), b), OR(a, NOT(b)))

In [4]:
n = 10

In [5]:
A = np.random.rand(n).round(1)
A

array([0.3, 0.5, 0.9, 0.7, 0.5, 0.3, 0.1, 0.7, 0.5, 0.1])

In [6]:
B = np.random.rand(n).round(1)
B

array([0.3, 0.4, 0.8, 0.9, 0.4, 0.3, 0.7, 0.2, 0.9, 0.9])

In [7]:
C = np.random.rand(n).round(1)
C

array([0.2, 0.6, 0.3, 0.5, 0.8, 0.3, 0.1, 1. , 0.5, 0.3])

In [8]:
l_part = AND(A, (OR(B, NOT(C))))
r_part = (OR(NOT(A), AND(B, C)))

print(f"Left part of equation: {l_part}")
print(f"Right part of equation: {r_part}")

Left part of equation: [0.3 0.4 0.8 0.7 0.4 0.3 0.1 0.2 0.5 0.1]
Right part of equation: [0.7 0.5 0.3 0.5 0.5 0.7 0.9 0.3 0.5 0.9]


In [9]:
# f_5
IMP(l_part, r_part)

array([0.7, 0.6, 0.3, 0.5, 0.6, 0.7, 0.9, 0.8, 0.5, 0.9])

In [10]:
df = pd.DataFrame({"A": A, "B": B, "C": C, "NOT(A)": NOT(A), "AND(A, B)": AND(A, B), "OR(A, B)": OR(A, B), "IMP(A, B)": IMP(A, B), "EQU(A, B)": EQU(A, B), "AND(A, (OR(B, NOT(C)))) == (OR(NOT(A), AND(B, C)))": IMP(l_part, r_part)})
df

A    B    C  NOT(A)  AND(A, B)  OR(A, B)  IMP(A, B)  EQU(A, B)  \
0  0.3  0.3  0.2     0.7        0.3       0.3        0.7        0.7   
1  0.5  0.4  0.6     0.5        0.4       0.5        0.5        0.5   
2  0.9  0.8  0.3     0.1        0.8       0.9        0.8        0.8   
3  0.7  0.9  0.5     0.3        0.7       0.9        0.7        0.7   
4  0.5  0.4  0.8     0.5        0.4       0.5        0.5        0.5   
5  0.3  0.3  0.3     0.7        0.3       0.3        0.7        0.7   
6  0.1  0.7  0.1     0.9        0.1       0.7        0.9        0.3   
7  0.7  0.2  1.0     0.3        0.2       0.7        0.3        0.3   
8  0.5  0.9  0.5     0.5        0.5       0.9        0.5        0.5   
9  0.1  0.9  0.3     0.9        0.1       0.9        0.9        0.1   

   AND(A, (OR(B, NOT(C)))) == (OR(NOT(A), AND(B, C)))  
0                                                0.7   
1                                                0.6   
2                                                0.3   
3                                                0.5   
4                                                0.6   
5                                                0.7   
6                                                0.9   
7                                                0.8   
8                                                0.5   
9                                                0.9